export const canvas = document.getElementById('canvas')
export const ctx = canvas.getContext('2d')
export const pointListElement = document.getElementById('points')
export const resetButton = document.getElementById('resetButton')
export const instructionSign = document.getElementById('instructionSign')
export const aboutButton = document.getElementById('aboutButton')
export const modal = document.getElementById('modal')
export const closeButton = document.getElementById('close')
